### ISSUE TITLE
Version 1.7.7 in Lab 03 of Day 1 non longer supported in az cli

### ISSUE THREAD

**Issue by feranto** [Azure/blackbelt-aks-hackfest#104]
Using:

az aks create -n $CLUSTER_NAME -g $NAME -c 2 -k 1.7.7 --generate-ssh-keys -l $LOCATION

Now gives the following message:

Operation failed with status: 'Bad Request'. Details: RBAC feature is not supported with theselected Kubernetes version. The version of Kubernetes must be 1.8.x or higher

**Comment by swgriffith** [comment]
With the latest cli it's assumed that you want rbac enabled. You can disable with --disable-rbac. I've created a PR for the lab doc.
[https://github.com/Azure/blackbelt-aks-hackfest/pull/105](url)

**Comment by swgriffith** [comment]
FYI - There's a kubectl version dependency as well. I closed the PR so I can recreate with both fixes.

**Comment by mathieu-benoit** [comment]
FYI @swgriffith and @feranto, while implementing this PR #108, the Kubernetes version will be set to 1.10.6 and will take into account this feedback.
