### ISSUE TITLE
Kubernetes dashboard can be viewed using `az aks browse` to simplify instructions

### ISSUE THREAD

**Issue by clarenceb** [Azure/blackbelt-aks-hackfest#106]
In `labs/day1-labs/05-kubernetes-ui.md` the suggested way to view the Kubernetes dashboard is to get the cluster credentials (for `kubectl`) then run `kubectl proxy` and finally browse to a long URL.

You can just use `az aks browse -n $CLUSTER_NAME -g $NAME` to achieve the same thing in one command.  Any particular reason to not change the instructions to say this?

**Comment by mathieu-benoit** [comment]
Could be now closed since PR https://github.com/Azure/blackbelt-aks-hackfest/pull/109 has been merged into master.
