### ISSUE TITLE
Day 1, Lab 2: Docker user-defined networks provide DNS so you don't need to use IP addresses

### ISSUE THREAD

**Issue by clarenceb** [Azure/blackbelt-aks-hackfest#107]
In `labs/day1-labs/02-dockerize-apps.md` a user-defined bridge network is created with a specific subnet and then the 3 docker containers are started using IPs like so:

```sh
docker network create --subnet=172.18.0.0/16 my-network
docker run -d --name db --net my-network --ip 172.18.0.10 -p 27017:27017 rating-db
docker run -d --name api -e "MONGODB_URI=mongodb://172.18.0.10:27017/webratings" --net my-network --ip 172.18.0.11 -p 3000:3000 rating-api
docker run -d --name web -e "API=http://172.18.0.11:3000/" --net my-network --ip 172.18.0.12 -p 8080:8080 rating-web
```
Using IPs is both unnessary and also confusing for readers.

You can achieve the same thing by using the container names instead of IPs:

```sh
docker network create my-network
docker run -d --name db --net my-network -p 27017:27017 rating-db
docker run -d --name api -e "MONGODB_URI=mongodb://db:27017/webratings" --net my-network -p 3000:3000 rating-api
docker run -d --name web -e "API=http://api:3000/" --net my-network -p 8080:8080 rating-web
```

User-defined networks in Docker provide built-in DNS so you don't need to refer to containers by their IPs.

**Comment by mathieu-benoit** [comment]
Could be now closed since PR https://github.com/Azure/blackbelt-aks-hackfest/pull/110 has been merged into master.
