### ISSUE TITLE
LAB 3 - AKS 1.11.1 not available

### ISSUE THREAD

**Issue by iYoungblood** [Azure/blackbelt-aks-hackfest#114]
1.11.1 is no longer available.

1.11.2 and 1.11.3 are available.

**Comment by mathieu-benoit** [comment]
Good point, thanks for the feedback! 

k8s 1.11.2 and helm 2.11.0: #115

**Comment by dstrebel** [comment]
Addressed and merged in [#115](https://github.com/Azure/blackbelt-aks-hackfest/pull/115)
