### ISSUE TITLE
check permissions on import.sh script in container

### ISSUE THREAD

**Issue by dstrebel** [Azure/blackbelt-aks-hackfest#31]

**Comment by chzbrgr71** [comment]
did someone get an error? I looked at permissions and the file is marked executable and looks open

```
-rwxr-xr-x  1 brianredmond  staff    329 Jan 17 09:00 import.sh
```

**Comment by jschluchter** [comment]
Is this still an issue, or can we close?

**Comment by dstrebel** [comment]
This seemed to only happen with one user, so closing it as might of been some issue during reconfigure between aks->acs
