### ISSUE TITLE
aks resource group create needs to be in a aks region

### ISSUE THREAD

**Issue by anujb** [Azure/blackbelt-aks-hackfest#39]
https://github.com/Azure/blackbelt-aks-hackfest/blob/master/linux-container-workshop/hol-content/02-dockerize-apps.md

Need to call out that when `az group create ...` is called that it needs to be in a region that supports AKS, otherwise you will get an error like this – 

$ az aks create -n $NAME -g $NAME -c 2 -k 1.7.7 --generate-ssh-keys
The provided location 'westus' is not available for resource type 'Microsoft.ContainerService/managedClusters'. List of available regions for the resource type is 'eastus,westeurope,centralus,canadacentral,canadaeast,westus2'.

**Comment by jschluchter** [comment]
The rg is auto created for the specifically for this lab. (3rd party generating the Azure subs). I believe its just eastus actually, but after speaking to the AKS team, central & east are viable.

**Comment by chzbrgr71** [comment]
updated
