### ISSUE TITLE
When viewing dashboard describe concepts: NodePool, Pods, etc.

### ISSUE THREAD

**Issue by anujb** [Azure/blackbelt-aks-hackfest#42]
https://github.com/Azure/blackbelt-aks-hackfest/blob/master/linux-container-workshop/hol-content/05-kubernetes-ui.md

**Comment by jschluchter** [comment]
Not sure how into the weeds we want to go here. Willing to bring @chzbrgr71 , @evillgenius75 , and @dstrebel to the convo for their thoughts.

**Comment by evillgenius75** [comment]
I am not sure the portal does the relationship of the all of the objects justice. Maybe if we use the portion of the slides that graphically lay out the relationship of all the objects and use the portal to show it in relation to the deployment they made.  But I wouldn't spend too much time as most people are not using the K8s UI in real world applications.

**Comment by chzbrgr71** [comment]
Maybe we direct people to kubernetes.io for additional details on concepts?

**Comment by chzbrgr71** [comment]
added link to kubernetes.io
