### ISSUE TITLE
Leaderboard 4 super hero images absent when using cosmosdb backend

### ISSUE THREAD

**Issue by naseemkullah** [Azure/blackbelt-aks-hackfest#49]
Hi I noticed that the 4 super hero images in the leaderboard section are absent when using cosmosdb as backend. is something lost along the dump and restore from the mongodb pod?

**Comment by jschluchter** [comment]
Are you positive this isn't a workflow issue? We specifically did this workshop in Nashville on 2/7 with no issues.

**Comment by naseemkullah** [comment]
I'm sure of nothing but

this is what it looks like when migrated to cosmosdb
![image](https://user-images.githubusercontent.com/24660299/36070526-4b75c9c6-0eca-11e8-865e-ee332ea7e169.png)


this is what is looked like running on mongodb pod
https://files.slack.com/files-pri/T53R1TAT0-F94Q7PF0C/image.png

**Comment by chzbrgr71** [comment]
I just did an end to end test yesterday and the images appeared on CosmosDB. It could be that the name of the collection or db is wrong in your connect string. Our instructions were not clear (this was fixed yesterday). You can check the logs on your API container and see. When those images are blank, something is generally wrong.

**Comment by naseemkullah** [comment]
OK, thanks!
