### ISSUE TITLE
Step 10 needs more beer.

### ISSUE THREAD

**Issue by BarDweller** [Azure/blackbelt-aks-hackfest#63]
https://github.com/Azure/blackbelt-aks-hackfest/blob/master/linux-container-workshop/hol-content/10-cluster-upgrading.md

This step says to use `az aks get-versions` which doesn't work.. 
```
$ az aks get-versions
az aks get-versions: error: the following arguments are required: --location/-l
usage: az aks get-versions [-h] [--verbose] [--debug]
                           [--output {json,jsonc,table,tsv}]
                           [--query JMESPATH] --location LOCATION
```

I suspect it wants us to use `az aks get-upgrades` except it never explains how to set $AKS_CLUSTER_NAME or $RESOURCE_GROUP_NAME

Reusing the vars from the earlier steps.. I guessed at.. 
```
NAME=$(az group list | jq '.[0]."name"' -r)
CLUSTER_NAME="${NAME//_}"
AKS_CLUSTER_NAME=$CLUSTER_NAME
RESOURCE_GROUP_NAME=$NAME
```

Either the page needs to use the old vars and explain how to set them, or it should show how to set the new vars used on that page. 

Page also needs more beer. Amount consumed while writing this page was insufficient leading to inconsistencies.

**Comment by mathieu-benoit** [comment]
Thanks @BarDweller for the feedback! Like discussed, this PR #64 is tackling these feedback for more consistency across all the labs. Thanks!

**Comment by jschluchter** [comment]
Please take a look chzbrgr71@7ba8d51

This change was made yesterday

**Comment by mathieu-benoit** [comment]
@jschluchter , interesting one, why it's not in `master`? Furthermore, we are tackling the feedback documented by this issue here: PR #64 .

**Comment by mathieu-benoit** [comment]
PR #64 closed and merged into master, we could close this issue.

**Comment by chzbrgr71** [comment]
merged
