### ISSUE TITLE
Use --password-stdin

### ISSUE THREAD

**Issue by snpdev** [Azure/blackbelt-aks-hackfest#74]
For users using their own jumpbox, on the HOL #2 step:
```
docker login --username $ACR_USER --password $ACR_PWD $ACR_SERVER
```
... they may receive the following message:
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
```
The solution is to use vi to write the password to a txt file (e.g. ~/acr-pw.txt) and then use this alternative login command:
```
 cat ~/acr-pw.txt | docker login $ACR_SERVER -u $ACR_USER --password-stdin
```
Is this deserving of a PR? Perhaps it's a bit out of scope.

**Comment by chzbrgr71** [comment]
This is probably out of scope and might only lead to confusion. Some things are good to leave in there and lead to questions and discussion.
