### ISSUE TITLE
Switch to B-series VM size?

### ISSUE THREAD

**Issue by snpdev** [Azure/blackbelt-aks-hackfest#75]
Now that AKS has [B-series VM support](https://azure.microsoft.com/en-us/blog/introducing-burstable-vm-support-in-aks/), should we change HOL 3 to use a B-series VM?

Otherwise the more expensive Standard_DS1_v2 default is used.

I imagine Standard_B1ms would be fine, but perhaps Standard_B1s would suffice (see [B-series VM options](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/b-series-burstable)). I have not tested.

The new command line would be along the lines of...
```
az aks create -n $CLUSTER_NAME -g $NAME -c 2 -k 1.7.7 --node-vm-size=Standard_B1ms --generate-ssh-keys -l eastus
````

Thoughts?

**Comment by chzbrgr71** [comment]
I'm opposed to changing the VM size right now

**Comment by jschluchter** [comment]
I agree with @chzbrgr71 on this, not really necessary at this point. Closing.
