### ISSUE TITLE
OSBA Cosmos Class Missing

### ISSUE THREAD

**Issue by ryankmcintyre** [Azure/blackbelt-aks-hackfest#89]
In the [OSBA lab using Cosmos](https://github.com/Azure/blackbelt-aks-hackfest/blob/master/labs/day2-labs/open-service-broker.md) it's using the class azure-cosmos-mongo-db. Doesn't look like that class exists any longer as running apply results in 
`
Error from server (Forbidden): error when creating "heroes-cosmosdb.yaml": serviceinstances.servicecatalog.k8s.io "heroes-cosmosdb-instance" is forbidden: ClusterServiceClass {ClassExternalName:"azure-cosmos-mongo-db"} does not exist, can not figure out the default ClusterServicePlan.
`
I ran `./svcat get classes` and azure-cosmos-mongo-db wasn't listed.

**Comment by snpdev** [comment]
I faced the same problem today.  I do see the service listed in:
https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/cosmosdb.md#service-azure-cosmosdb-mongo-account 

What might account for this problem? Prior steps in the lab completed successfully.

**Comment by chzbrgr71** [comment]
The service class was renamed to `azure-cosmosdb-mongo-account` but we did update the yaml accordingly. Can you paste the new error message you are seeing?

**Comment by snpdev** [comment]
The error we had today is:
`
Error from server (Forbidden): error when creating "heroes-cosmosdb.yaml": serviceinstances.servicecatalog.k8s.io "heroes-cosmosdb-instance" is forbidden: ClusterServiceClass {ClassExternalName:"azure-cosmosdb-mongo-account"} does not exist, can not figure out the default ClusterServicePlan.
`
So, same error with the renamed service class.

**Comment by snpdev** [comment]
Into Azure Shell, the command was copied verbatim from the lab instructions. We'll be mindful of this when testing again. Thanks.

**Comment by jayachandralingam** [comment]
I have sucessfully completed the OSBA lab as per instruction mentioned, only change I made from above comments is service class name `azure-cosmosdb-mongo-account` .

**Comment by lastcoolnameleft** [comment]
I have verified that I am able to complete the OSBA lab as per the current instructions.

**Comment by mathieu-benoit** [comment]
FYI @chzbrgr71 or @jschluchter , this issue could be now closed since PR #108 has been merged into master.
